### PR TITLE
Add CustomFunction2 interface support

### PR DESCRIPTION
**Pull request by dhleong**
This is a first pass of #57. Includes a couple tests.

Let me know what you think!

### CODE REVIEW

**Comment by npurushe** [comment]
Hi I think overall your changes are great! Thanks! 

API wise I think your custom function interface is overall better than what's there currently, so it makes sense to call it just `Function` instead of `CustomFunction2`, and update the corresponding methods to match e.g. `SqliteFunction`. I think the original `CustomFunction` can be marked as deprecated and this can simply be the preferred way instead.

**Comment by dhleong** [comment]
Great! I'll rename everything and `@Deprecated` CustomFunction probably sometime this weekend

**Comment by dhleong** [comment]
Done

**Comment by npurushe** [comment]
Great thanks!

**Pull request merged**
